/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.HelpController;

/**
 *
 * @author andras
 */
public class HelpDialog extends javax.swing.JDialog {
    public HelpController helpController = new HelpController(this);
    public Mainwindow mainwindow;
    /**
     * Creates new form HelpDialog
     */
    public HelpDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
//        super.setLocationRelativeTo(parent);
        setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        helpToolBarPanel = new javax.swing.JPanel();
        helpToolBar = new javax.swing.JToolBar();
        closeButton = new javax.swing.JButton();
        helpContentPanel = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        helpTree = new javax.swing.JTree();
        helpContentScrollPane = new javax.swing.JScrollPane();
        helpTextPane = new javax.swing.JTextPane();

        jScrollPane1.setViewportView(jTree1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        helpToolBarPanel.setLayout(new java.awt.GridLayout(1, 0));

        helpToolBar.setRollover(true);

        closeButton.setText("Close");
        closeButton.setFocusable(false);
        closeButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        closeButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        helpToolBar.add(closeButton);

        helpToolBarPanel.add(helpToolBar);

        getContentPane().add(helpToolBarPanel);

        helpContentPanel.setLayout(new java.awt.GridLayout(1, 0));

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("jWordSearch");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("About");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Usage");
        treeNode1.add(treeNode2);
        helpTree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        helpTree.setMaximumSize(new java.awt.Dimension(200, 72));
        helpTree.setPreferredSize(new java.awt.Dimension(150, 72));
        helpTree.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                helpTreeMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(helpTree);

        jSplitPane1.setLeftComponent(jScrollPane2);

        helpTextPane.setContentType("text/html"); // NOI18N
        helpTextPane.setPreferredSize(new java.awt.Dimension(400, 21));
        helpContentScrollPane.setViewportView(helpTextPane);

        jSplitPane1.setRightComponent(helpContentScrollPane);

        helpContentPanel.add(jSplitPane1);

        getContentPane().add(helpContentPanel);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        helpController.closeButtonActionPerformed(evt);
    }//GEN-LAST:event_closeButtonActionPerformed

    private void helpTreeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpTreeMouseClicked
        helpController.helpTreeMouseClicked(evt);
    }//GEN-LAST:event_helpTreeMouseClicked

    public void setMainwindow(Mainwindow mainwindow) {
        this.mainwindow = mainwindow;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HelpDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HelpDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HelpDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HelpDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                HelpDialog dialog = new HelpDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JPanel helpContentPanel;
    private javax.swing.JScrollPane helpContentScrollPane;
    public javax.swing.JTextPane helpTextPane;
    private javax.swing.JToolBar helpToolBar;
    private javax.swing.JPanel helpToolBarPanel;
    public javax.swing.JTree helpTree;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables
}
