/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.OptionsController;

/**
 *
 * @author andras
 */
public class OptionsDialog extends javax.swing.JDialog {
    public OptionsController optionsController;
    /**
     * Creates new form OptionsDialog
     */
    public OptionsDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        super.setLocationRelativeTo(parent);
        optionsController = new OptionsController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        containerPanel = new javax.swing.JPanel();
        authorSetupPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        authorTextField = new javax.swing.JTextField();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(100, 0), new java.awt.Dimension(100, 0), new java.awt.Dimension(100, 32767));
        helpFilePathPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        helpFilePathTextField = new javax.swing.JTextField();
        browseHelpFilePathButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        applyOptionsButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();
        spacerPanel = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 200), new java.awt.Dimension(0, 200), new java.awt.Dimension(32767, 100));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        containerPanel.setLayout(new javax.swing.BoxLayout(containerPanel, javax.swing.BoxLayout.PAGE_AXIS));

        authorSetupPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Author setup"));
        authorSetupPanel.setLayout(new javax.swing.BoxLayout(authorSetupPanel, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setText("Author name:");
        authorSetupPanel.add(jLabel1);

        authorTextField.setMinimumSize(new java.awt.Dimension(4, 30));
        authorSetupPanel.add(authorTextField);
        authorSetupPanel.add(filler2);

        containerPanel.add(authorSetupPanel);

        helpFilePathPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Help file path"));
        helpFilePathPanel.setLayout(new javax.swing.BoxLayout(helpFilePathPanel, javax.swing.BoxLayout.LINE_AXIS));

        jLabel2.setText("Help file path:");
        helpFilePathPanel.add(jLabel2);

        helpFilePathTextField.setMaximumSize(new java.awt.Dimension(2147483647, 30));
        helpFilePathPanel.add(helpFilePathTextField);

        browseHelpFilePathButton.setText("Browse");
        browseHelpFilePathButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseHelpFilePathButtonActionPerformed(evt);
            }
        });
        helpFilePathPanel.add(browseHelpFilePathButton);

        containerPanel.add(helpFilePathPanel);

        applyOptionsButton.setText("Apply options");
        applyOptionsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyOptionsButtonActionPerformed(evt);
            }
        });

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(139, Short.MAX_VALUE)
                .addComponent(applyOptionsButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(closeButton)
                .addGap(45, 45, 45))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(applyOptionsButton)
                    .addComponent(closeButton)))
        );

        containerPanel.add(jPanel1);

        spacerPanel.setLayout(new java.awt.GridLayout(1, 0));
        spacerPanel.add(filler1);

        containerPanel.add(spacerPanel);

        getContentPane().add(containerPanel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void browseHelpFilePathButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseHelpFilePathButtonActionPerformed
        optionsController.browseHelpFilePathButtonActionPerformed(evt);
    }//GEN-LAST:event_browseHelpFilePathButtonActionPerformed

    private void applyOptionsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyOptionsButtonActionPerformed
        optionsController.applyOptionsButtonActionPerformed(evt);
    }//GEN-LAST:event_applyOptionsButtonActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        optionsController.closeButtonActionPerformed(evt);
    }//GEN-LAST:event_closeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) { //NOI18N
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OptionsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OptionsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OptionsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OptionsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                OptionsDialog dialog = new OptionsDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton applyOptionsButton;
    private javax.swing.JPanel authorSetupPanel;
    public javax.swing.JTextField authorTextField;
    private javax.swing.JButton browseHelpFilePathButton;
    private javax.swing.JButton closeButton;
    private javax.swing.JPanel containerPanel;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JPanel helpFilePathPanel;
    public javax.swing.JTextField helpFilePathTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel spacerPanel;
    // End of variables declaration//GEN-END:variables
}
